/**
 * src/pages/admin/students/data.js
 * ─────────────────────────────────────────────────────────────
 * Shared in-memory data + helpers for the student sub-module.
 * In a real app, replace this with API calls via studentsApi.
 */

export const CLASSES = [
  "6-A","6-B","6-C",
  "7-A","7-B",
  "8-A","8-B",
  "9-A","9-B",
  "10-A","10-B",
  "11-A","11-B",
];

export const BLOOD_GROUPS = ["A+","A-","B+","B-","AB+","AB-","O+","O-"];

export const STUDENTS = [
  {
    id: "1",
    admNo: "EDN-2021-1284",
    name: "Aryan Mehta",
    dob: "14 Aug 2010",
    gender: "Male",
    class: "9-A",
    roll: 21,
    section: "A",
    father: "Rakesh Mehta",
    mother: "Priya Mehta",
    phone: "+91 98765 43210",
    altPhone: "+91 98765 43211",
    email: "r.mehta@example.com",
    address: "42-B Shanti Nagar, Andheri West, Mumbai 400058",
    blood: "B+",
    status: "Active",
    fees: "Paid",
    attendance: 96,
    admissionDate: "3 Jun 2021",
    house: "Tagore House",
    classTeacher: "Ms. D'Souza",
    nationality: "Indian",
    religion: "Hindu",
    category: "General",
    previousSchool: "St. Mary's Primary School",
    emergencyContact: "+91 98765 43212",
  },
  {
    id: "2",
    admNo: "EDN-2021-1285",
    name: "Priya Sharma",
    dob: "22 Mar 2009",
    gender: "Female",
    class: "11-B",
    roll: 7,
    section: "B",
    father: "Suresh Sharma",
    mother: "Kavita Sharma",
    phone: "+91 98765 43220",
    altPhone: "",
    email: "s.sharma@example.com",
    address: "15 Park Avenue, Bandra, Mumbai 400050",
    blood: "O+",
    status: "Active",
    fees: "Partial",
    attendance: 88,
    admissionDate: "1 Jun 2021",
    house: "Gandhi House",
    classTeacher: "Mr. Kapoor",
    nationality: "Indian",
    religion: "Hindu",
    category: "OBC",
    previousSchool: "Bright Future School",
    emergencyContact: "+91 98765 43221",
  },
  {
    id: "3",
    admNo: "EDN-2022-1410",
    name: "Rohan Kulkarni",
    dob: "5 Jul 2012",
    gender: "Male",
    class: "6-C",
    roll: 14,
    section: "C",
    father: "Anil Kulkarni",
    mother: "Sunita Kulkarni",
    phone: "+91 98765 43230",
    altPhone: "+91 98765 43231",
    email: "a.kulkarni@example.com",
    address: "7 Rose Garden, Powai, Mumbai 400076",
    blood: "A+",
    status: "Active",
    fees: "Overdue",
    attendance: 72,
    admissionDate: "4 Jun 2022",
    house: "Nehru House",
    classTeacher: "Ms. Iyer",
    nationality: "Indian",
    religion: "Hindu",
    category: "General",
    previousSchool: "Sunrise Academy",
    emergencyContact: "+91 98765 43232",
  },
  {
    id: "4",
    admNo: "EDN-2020-1100",
    name: "Sneha Nair",
    dob: "18 Nov 2008",
    gender: "Female",
    class: "10-A",
    roll: 2,
    section: "A",
    father: "Vijay Nair",
    mother: "Leela Nair",
    phone: "+91 98765 43240",
    altPhone: "",
    email: "v.nair@example.com",
    address: "22 Coconut Lane, Malad, Mumbai 400064",
    blood: "B-",
    status: "Inactive",
    fees: "Paid",
    attendance: 91,
    admissionDate: "1 Jun 2020",
    house: "Tagore House",
    classTeacher: "Dr. Rao",
    nationality: "Indian",
    religion: "Christian",
    category: "General",
    previousSchool: "Holy Cross School",
    emergencyContact: "+91 98765 43241",
  },
  {
    id: "5",
    admNo: "EDN-2022-1411",
    name: "Vikram Joshi",
    dob: "9 Sep 2011",
    gender: "Male",
    class: "8-B",
    roll: 31,
    section: "B",
    father: "Deepak Joshi",
    mother: "Meena Joshi",
    phone: "+91 98765 43250",
    altPhone: "+91 98765 43251",
    email: "d.joshi@example.com",
    address: "9 Lotus Street, Goregaon, Mumbai 400063",
    blood: "AB+",
    status: "Active",
    fees: "Partial",
    attendance: 85,
    admissionDate: "5 Jun 2022",
    house: "Gandhi House",
    classTeacher: "Mr. Sharma",
    nationality: "Indian",
    religion: "Hindu",
    category: "General",
    previousSchool: "New Horizon School",
    emergencyContact: "+91 98765 43252",
  },
  {
    id: "6",
    admNo: "EDN-2023-1560",
    name: "Neha Kulkarni",
    dob: "1 Feb 2012",
    gender: "Female",
    class: "7-A",
    roll: 9,
    section: "A",
    father: "Ramesh Kulkarni",
    mother: "Asha Kulkarni",
    phone: "+91 98765 43260",
    altPhone: "",
    email: "r.kulkarni@example.com",
    address: "33 Hill View, Thane, Mumbai 400601",
    blood: "O-",
    status: "Active",
    fees: "Paid",
    attendance: 98,
    admissionDate: "2 Jun 2023",
    house: "Nehru House",
    classTeacher: "Ms. Pillai",
    nationality: "Indian",
    religion: "Hindu",
    category: "SC",
    previousSchool: "Rainbow School",
    emergencyContact: "+91 98765 43261",
  },
];

export const FEE_VARIANT    = { Paid: "success", Partial: "warning", Overdue: "danger" };
export const STATUS_VARIANT = { Active: "success", Inactive: "neutral", Suspended: "danger" };