/**
 * src/pages/admin/teachers/data.js
 * ─────────────────────────────────────────────────────────────
 * Shared in-memory data for the teacher sub-module.
 * Replace with teachersApi calls in production.
 */

export const ALL_CLASSES = [
  "6-A","6-B","6-C","7-A","7-B",
  "8-A","8-B","9-A","9-B","10-A","10-B","11-A","11-B",
];

export const SUBJECTS = [
  "Mathematics","English","Science","Social Studies",
  "Hindi","Computer Sci.","Physical Ed.","Art","Music","Sanskrit",
];

export const TEACHERS = [
  {
    id: "1",
    empId: "TCH-2012-001",
    name: "Suresh Kapoor",
    subject: "Mathematics",
    qualification: "M.Sc Mathematics",
    experience: 12,
    joined: "Aug 2012",
    dob: "10 May 1980",
    gender: "Male",
    phone: "+91 98200 11001",
    altPhone: "",
    email: "s.kapoor@edunova.app",
    address: "14 Maple Street, Andheri, Mumbai 400053",
    classes: ["9-A","10-B"],
    salary: 52000,
    status: "Active",
    blood: "O+",
    nationality: "Indian",
    religion: "Hindu",
    category: "General",
    emergencyContact: "+91 98200 11099",
    bio: "Dedicated mathematics teacher with 12 years of experience teaching CBSE curriculum up to Class 12.",
  },
  {
    id: "2",
    empId: "TCH-2016-002",
    name: "Priya D'Souza",
    subject: "English",
    qualification: "M.A. English Literature",
    experience: 8,
    joined: "Jun 2016",
    dob: "3 Nov 1985",
    gender: "Female",
    phone: "+91 98200 11002",
    altPhone: "+91 98200 11003",
    email: "p.dsouza@edunova.app",
    address: "7 Palm Avenue, Bandra, Mumbai 400050",
    classes: ["11-A","11-B"],
    salary: 46000,
    status: "Active",
    blood: "A+",
    nationality: "Indian",
    religion: "Christian",
    category: "General",
    emergencyContact: "+91 98200 11098",
    bio: "Passionate English teacher specialising in literature and creative writing for senior secondary students.",
  },
  {
    id: "3",
    empId: "TCH-2009-003",
    name: "Ramesh Rao",
    subject: "Science",
    qualification: "M.Sc Physics, B.Ed",
    experience: 15,
    joined: "Jan 2009",
    dob: "22 Feb 1974",
    gender: "Male",
    phone: "+91 98200 11003",
    altPhone: "",
    email: "r.rao@edunova.app",
    address: "3 Oak Lane, Powai, Mumbai 400076",
    classes: ["6-C","7-A"],
    salary: 58000,
    status: "Active",
    blood: "B+",
    nationality: "Indian",
    religion: "Hindu",
    category: "OBC",
    emergencyContact: "+91 98200 11097",
    bio: "Senior science faculty with a focus on making physics and chemistry engaging through hands-on experiments.",
  },
  {
    id: "4",
    empId: "TCH-2018-004",
    name: "Anitha Iyer",
    subject: "Social Studies",
    qualification: "M.A. History",
    experience: 6,
    joined: "Mar 2018",
    dob: "15 Aug 1989",
    gender: "Female",
    phone: "+91 98200 11004",
    altPhone: "",
    email: "a.iyer@edunova.app",
    address: "21 Coconut Road, Malad, Mumbai 400064",
    classes: ["8-B","9-A"],
    salary: 44000,
    status: "Active",
    blood: "AB+",
    nationality: "Indian",
    religion: "Hindu",
    category: "General",
    emergencyContact: "+91 98200 11096",
    bio: "History and civics teacher committed to developing critical thinking and civic awareness in students.",
  },
  {
    id: "5",
    empId: "TCH-2014-005",
    name: "Vijay Menon",
    subject: "Hindi",
    qualification: "M.A. Hindi",
    experience: 10,
    joined: "Aug 2014",
    dob: "30 Jan 1982",
    gender: "Male",
    phone: "+91 98200 11005",
    altPhone: "+91 98200 11006",
    email: "v.menon@edunova.app",
    address: "9 Lotus Street, Goregaon, Mumbai 400063",
    classes: ["6-A","6-B"],
    salary: 42000,
    status: "On Leave",
    blood: "O-",
    nationality: "Indian",
    religion: "Hindu",
    category: "General",
    emergencyContact: "+91 98200 11095",
    bio: "Hindi language and literature teacher currently on approved medical leave. Expected to return in May 2026.",
  },
  {
    id: "6",
    empId: "TCH-2019-006",
    name: "Nita Pillai",
    subject: "Computer Sci.",
    qualification: "B.E. Computer Science",
    experience: 5,
    joined: "Jul 2019",
    dob: "19 Jun 1991",
    gender: "Female",
    phone: "+91 98200 11006",
    altPhone: "",
    email: "n.pillai@edunova.app",
    address: "55 Silver Oak, Thane, Mumbai 400601",
    classes: ["10-A","11-A"],
    salary: 48000,
    status: "Active",
    blood: "B-",
    nationality: "Indian",
    religion: "Hindu",
    category: "General",
    emergencyContact: "+91 98200 11094",
    bio: "Computer science teacher specialising in Python programming and web development for senior classes.",
  },
];

export const STATUS_VARIANT = {
  Active:     "success",
  "On Leave": "warning",
  Inactive:   "neutral",
};